/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Communication } from "./Communication";
export * as factories from "./factories";
export { Communication__factory } from "./factories/Communication__factory";
